### PR TITLE
New files added and updates made

### PR DESCRIPTION
**Pull request by johnpaulchukwu43**

### CODE REVIEW

**Comment by gbozee** [comment]
Congratulations. You successfully got all the tests to pass. You could send a mail at gbozee@gmail.com if you are still interested in the offer. In the mail please send me your phone number so that I can call you.

**Comment by gbozee** [comment]
After thoroughly going through your code, It appears that you copied the solution from a previous history because the variables naming are exactly the same. If you think this is false and that you implemented the solution yourself, then let me know and I would spin up another quiz similar to this one and you would have a deadline of a day to complete it.

**Comment by johnpaulchukwu43** [comment]
Yes I would take another quiz to prove myself

**Comment by gbozee** [comment]
I just added a new update to the current code base. An additional test. fork the repo, solve the final test and issue a pull request back. if you get this to work, I would be convinced. Good luck

**Pull request closed without merging**
